/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TebInterface */

#ifndef _Included_TebInterface
#define _Included_TebInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TebInterface
 * Method:    plan
 * Signature: (LPoseSE2;LPoseSE2;LPoseSE2;Z)LPoseSE2;
 */
JNIEXPORT jobject JNICALL Java_TebInterface_plan
  (JNIEnv *, jclass, jobject, jobject, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
